# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yhukeQQ1mYw0XXrOaJ1I8oQ0486ka8HJ
"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

def KNNClassifier(train_data,train_label,test_data,test_label):
    best_n  = [1,3,5,7]
    score = []
    for i,neighbour in zip(range(len(best_n )),best_n ):
        print("When Neighbour = " + "[" + str(neighbour) + "]")
        KnnTest = KNeighborsClassifier(n_neighbors = neighbour, weights = 'distance') 
        KnnTest.fit(train_data.T, train_label) 
        pred = KnnTest.predict(test_data.T)
        score.append(accuracy_score(output,test_label)) 
        print("Accuracy score is: " + str(score[i]))
        count = 0
        for i in range(len(output)):
            print("[" + str(i) + "]" + "Classified as: "+ str(pred[i]) +" Actual is: "+ str(test_label[i]))
            if((output[i]) != (score[i])):
                print("Misclassified")
                count+=1
    print("Number of Misclassified is " + str(count))
    plt.plot(score,best_n)
    plt.show()

