# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yhukeQQ1mYw0XXrOaJ1I8oQ0486ka8HJ
"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

def KNN(X_train,y_train,X_test,y_test):
    best_n = [1,3,5,7]
    score = []
    for i in best_n:
        neigh = KNeighborsClassifier(n_neighbors=i)
        neigh.fit(X_train, y_train)
        pred = neigh.predict(Xtest)
        score.append((i,accuracy_score(y_test,pred)))

    return max(score,key= lambda x:x[1])

#X_train_test 10% of X_train
n,score = KNN(X_train,y_train,X_train_test,y_train_test)
neigh = KNeighborsClassifier(n_neighbors=n)
neigh.fit(X_train, y_train)
pred = neigh.predict(Xtest)
score.append((i,accuracy_score(y_test,pred)))